name: Lint

on:
    push:
        branches:
            - master
        paths:
            - '**.php'
    pull_request:
        types: [opened, edited, synchronize, reopened]
        paths:
            - '**.php'

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer vendor directory
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Fix any standard violations we can
              run: composer run-script fix

            - name: Detecting PHP Code Standards Violations
              run: composer run-script lint
